curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

sudo dpkg -i cloudflared.deb

sudo cloudflared service install eyJhIjoiZWJiZTE2YWMzZTY4NGNmYjljZTJjZTdkOWNhNTRiMmIiLCJ0IjoiYjQ1OGQ2NDEtOTMxNC00ZmNhLWIyNzQtNmJhZDNiNmI5NTUyIiwicyI6Ik5qZzBZek14TTJZdE56azRaaTAwWmpRNExUZzVaVFl0WldOaE1URTRORGhpTmpZNCJ9
