curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb 

sudo dpkg -i cloudflared.deb

sudo cloudflared service install eyJhIjoiZWJiZTE2YWMzZTY4NGNmYjljZTJjZTdkOWNhNTRiMmIiLCJ0IjoiODRiY2Q2MWUtYWI2NC00NDRiLWE2YzEtN2RlNTM1MzFjY2Y1IiwicyI6IllqRmhNV1F5WXpJdE9XWTVPUzAwWWpZNUxXRXdNemN0TURjMk5UQXlPVE5tWmpWbCJ9
