curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb 

sudo dpkg -i cloudflared.deb

sudo cloudflared service install eyJhIjoiZWJiZTE2YWMzZTY4NGNmYjljZTJjZTdkOWNhNTRiMmIiLCJ0IjoiN2YxYjlhNDEtZWIxZC00ZTVlLTk2NGUtYzYxNDQ1YTA4OTAyIiwicyI6IllqZzBPV1psWWpVdE1UUTBOUzAwTldNNUxUbGtNamt0WlRBNE1tUTBZbU14TVRGbCJ9
