curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb

sudo dpkg -i cloudflared.deb

sudo cloudflared service install eyJhIjoiZWJiZTE2YWMzZTY4NGNmYjljZTJjZTdkOWNhNTRiMmIiLCJ0IjoiNDM4OTJhYjUtNTk4MC00NDMwLTliNjktNWQ2MGJkMmI1Yzk5IiwicyI6Ik5ERTBNVGhpTkdNdE0yUXdaaTAwWXpJNExUbG1ZVFl0TnpZNVl6SmpORGRtTVdSayJ9
